stages:
  - build
  - test

mdbook:
  stage: build
  image:
    name: peaceiris/mdbook:latest
    entrypoint: [""] # force an empty entrypoint
  script:
  - ./unused_pages.sh
  - mdbook build
  artifacts:
    paths:
      - book

lychee:
  stage: test
  image:
    name: lycheeverse/lychee:latest-alpine
    entrypoint: [""] # force an empty entrypoint
  script:
  - lychee --no-progress --offline --root-dir $(pwd)/book ./book
