image : hrektts/mdbook:latest

before_script:
  - apt-get update -qq
  - apt-get install -qq libssl-dev pkg-config build-essential curl git

build:
  script:
    - ./unused_pages.sh
    - mdbook build

